naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
  PackageNaming:
    active: false
complexity:
  LongParameterList:
    functionThreshold: 6
    ignoreDefaultParameters: true
  LongMethod:
    active: false
    threshold: 50
  LargeClass:
    active: true
    threshold: 350
style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  MaxLineLength:
    active: true
    maxLineLength: 120
  NewLineAtEndOfFile:
    active: false
